// SKRAPERS — Stage 3
// Computes investigation signals FROM REAL ACCOUNT DATA — no hardcoded
// verdicts, no hidden "isSkraper" shortcut read here. This is the
// confidence-not-certainty display the design doc calls for (section 9-10):
// qualitative signals the player weighs themselves, not a percentage or a
// SKRAPER DETECTED banner.
//
// Deliberately honest limitation, worth keeping visible rather than
// hiding: because every account (human and Skraper alike) is generated by
// the same Stage 0 template system, a signal like "sentence-length
// consistency" will NOT cleanly separate the two — which is thematically
// correct (the doc's own point in section 10-11: paranoia should not
// equal success, false positives have to be genuinely possible) but is
// also just an honest property of this prototype's content pipeline at
// this stage, not a solved detection problem.

(function () {

function cadenceSignal(posts) {
  if (posts.length < 3) {
    return { label: "Posting cadence", value: "not enough posts to judge", level: "low" };
  }
  const sorted = [...posts].sort((a, b) => a.timestamp - b.timestamp);
  const intervals = [];
  for (let i = 1; i < sorted.length; i++) intervals.push(sorted[i].timestamp - sorted[i - 1].timestamp);
  const mean = intervals.reduce((a, b) => a + b, 0) / intervals.length;
  const variance = intervals.reduce((a, b) => a + (b - mean) ** 2, 0) / intervals.length;
  const cv = mean > 0 ? Math.sqrt(variance) / mean : 0;
  // Low coefficient of variation = mechanically regular intervals = suspicious.
  const level = cv < 0.15 ? "high" : cv < 0.5 ? "medium" : "low";
  return { label: "Posting cadence", value: `interval variance ${(cv * 100).toFixed(0)}%`, level };
}

function activityPatternSignal(posts) {
  // Guard added after Stage 7 testing: a brand-new account with exactly
  // one post always has spreadRatio = 1/1 = 1.0, reading as maximally
  // suspicious purely from having too little data — a false-positive
  // generator built into the tool itself, not organic noise. The other
  // two signals already had this guard; this one didn't.
  if (posts.length < 3) {
    return { label: "Activity-hour pattern", value: "not enough posts to judge", level: "low" };
  }
  const hours = posts.map((p) => new Date(p.timestamp).getHours());
  const uniqueHours = new Set(hours).size;
  const spreadRatio = posts.length > 0 ? uniqueHours / posts.length : 0;
  // Posts scattered across many distinct hours with no clustering = no
  // circadian rhythm = suspicious (mirrors the doc's "strange activity
  // hours" clue in section 9).
  const level = spreadRatio > 0.85 ? "high" : spreadRatio > 0.5 ? "medium" : "low";
  return { label: "Activity-hour pattern", value: `${uniqueHours} distinct hours across ${posts.length} posts`, level };
}

function linguisticConsistencySignal(posts) {
  if (posts.length < 3) {
    return { label: "Linguistic consistency", value: "not enough posts to judge", level: "low" };
  }
  const lengths = posts.map((p) => p.text.length);
  const mean = lengths.reduce((a, b) => a + b, 0) / lengths.length;
  const variance = lengths.reduce((a, b) => a + (b - mean) ** 2, 0) / lengths.length;
  const cv = mean > 0 ? Math.sqrt(variance) / mean : 0;
  // Unlike the other two signals, low variance here is ambiguous by
  // design (see file header) — surfaced as medium rather than a false
  // "high" confidence claim the underlying data doesn't support.
  const level = cv < 0.1 ? "medium" : cv < 0.3 ? "low" : "low";
  return { label: "Linguistic consistency", value: `post-length variance ${(cv * 100).toFixed(0)}%`, level };
}

function computeSignals(account) {
  return [
    cadenceSignal(account.posts),
    activityPatternSignal(account.posts),
    linguisticConsistencySignal(account.posts),
  ];
}

// ===========================================================================
// Round 28 (#2/#3/#4): the DEEP signals — what a deep-investigate pull
// unlocks. Same contract as computeSignals above: every reading is computed
// from the account's own data (its `deep` record, generated at world-build
// time by simulation/worldgen.js's attachDeepSignals, and the follow graph),
// never from isSkraper or from the generator's own list of which tells it
// planted. Same qualitative low/medium/high shape, same "no verdicts" rule:
// a night-shift worker really does peak at 3am, a family really does share
// one photo, so every one of these can and does misfire on a real person.
// ===========================================================================

// In-fiction: the date ALGO// opened to the public. Chosen to sit before
// every hand-authored join date already in the game (the oldest is an
// event announcer's "Jan 2011", game/events.js), so no existing account is
// retroactively impossible. A server record older than this cannot be real.
const ALGO_LAUNCH = { year: 2010, month: 8, label: "Sep 2010" };
const MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function parseMonthYear(str) {
  const m = /^([A-Z][a-z]{2}) (\d{4})$/.exec(str || "");
  if (!m) return null;
  const month = MONTH_NAMES.indexOf(m[1]);
  return month === -1 ? null : { year: parseInt(m[2], 10), month };
}

function formatUtcOffset(utc) {
  const sign = utc < 0 ? "−" : "+";
  const abs = Math.abs(utc);
  const h = Math.floor(abs);
  const mins = Math.round((abs - h) * 60);
  return `UTC${sign}${h}${mins ? `:${String(mins).padStart(2, "0")}` : ""}`;
}

function hourLabel(h) {
  return `${String(((Math.round(h) % 24) + 24) % 24).padStart(2, "0")}:00`;
}

// Stated location vs. when the account is actually active, in that
// location's own local time (from the server-side session log — the feed's
// own timestamps are shown in the viewer's clock, so this is the one place
// the account's claimed timezone is checked at all).
function timezoneSignal(deep, account) {
  if (!deep.location) return null;
  const where = `${deep.location.city} (${formatUtcOffset(deep.location.utc)})`;
  if (typeof deep.activityPeak !== "number" || !(account.posts || []).length) {
    return { key: "timezone", label: "Stated location vs. activity", value: `${where} — no session activity to compare`, level: "low" };
  }
  const h = ((deep.activityPeak % 24) + 24) % 24;
  const level = h >= 1 && h <= 5 ? "high" : h === 0 || h === 6 ? "medium" : "low";
  const note = level === "high" ? " — the middle of the night where it says it lives" : level === "medium" ? " — unusually late or early" : "";
  return { key: "timezone", label: "Stated location vs. activity", value: `${where}; sessions peak around ${hourLabel(h)} local${note}`, level };
}

function photoSignal(deep) {
  const n = deep.photoMatches || 0;
  if (n >= 5) return { key: "photo", label: "Profile image match", value: `this image appears on ${n} other, unrelated profiles — a stock-library match`, level: "high" };
  if (n > 0) return { key: "photo", label: "Profile image match", value: `appears on ${n} other profile${n === 1 ? "" : "s"} — could be a shared or family photo`, level: "medium" };
  return { key: "photo", label: "Profile image match", value: "no matches elsewhere", level: "low" };
}

function recordSignal(deep, account) {
  const rec = parseMonthYear(deep.recordCreated);
  if (!rec) return { key: "record", label: "Account record", value: `server record consistent with "Joined ${account.joined || "unknown"}"`, level: "low" };
  const before = rec.year < ALGO_LAUNCH.year || (rec.year === ALGO_LAUNCH.year && rec.month < ALGO_LAUNCH.month);
  if (!before) return { key: "record", label: "Account record", value: `server record created ${deep.recordCreated}`, level: "low" };
  const months = (ALGO_LAUNCH.year - rec.year) * 12 + (ALGO_LAUNCH.month - rec.month);
  const span = months >= 24 ? `${Math.floor(months / 12)} years` : `${months} months`;
  return { key: "record", label: "Account record", value: `server record created ${deep.recordCreated} — ${span} before ALGO// launched (${ALGO_LAUNCH.label})`, level: "high" };
}

// Engagement history vs. what the account posts publicly. Each engagement
// item carries a `tone` assigned at generation time from what it actually
// IS relative to this account ("aligned": its own interests/its own
// network; "offtopic": unrelated but ordinary; "inflammatory": outrage/
// conspiracy content from outside the network; "cluster": another account's
// post, liked in a burst). The readout just counts them.
function summarizeEngagement(list) {
  const items = list || [];
  const total = items.length;
  const aligned = items.filter((e) => e.tone === "aligned").length;
  const inflammatory = items.filter((e) => e.tone === "inflammatory").length;
  const byMinute = {};
  items.forEach((e) => {
    if (e.kind !== "searched") byMinute[e.minsAgo] = (byMinute[e.minsAgo] || 0) + 1;
  });
  const burst = Math.max(0, ...Object.values(byMinute));
  return { total, aligned, inflammatory, burst };
}

function engagementSignal(deep) {
  const s = summarizeEngagement(deep.engagement);
  if (!s.total) return { key: "engagement", label: "Engagement vs. public posts", value: "no engagement on record", level: "medium" };
  const parts = [`${s.aligned} of ${s.total} match what it posts about`];
  if (s.inflammatory) parts.push(`${s.inflammatory} inflammatory`);
  if (s.burst >= 3) parts.push(`${s.burst} reactions in the same minute`);
  const ratio = s.aligned / s.total;
  const level = s.burst >= 3 || s.inflammatory >= 3 || ratio < 0.34 ? "high" : ratio < 0.67 || s.inflammatory >= 1 ? "medium" : "low";
  return { key: "engagement", label: "Engagement vs. public posts", value: parts.join(" · "), level };
}

// Follow reciprocity, one level deeper than the Connections panel's raw
// lists: how many of the accounts this one follows follow it back. Real
// people's follows are mostly mutual; an account that follows and is never
// followed back is reaching, not socialising. (A self-following cluster
// reads as mutual here — which is exactly why it's a soft signal.)
function reciprocitySignal(account, followerIds) {
  const following = account.following || [];
  if (!following.length) return { key: "reciprocity", label: "Follow reciprocity", value: `follows no one; followed by ${followerIds.length}`, level: followerIds.length ? "medium" : "low" };
  const back = following.filter((id) => followerIds.indexOf(id) !== -1).length;
  const ratio = back / following.length;
  // Only reaching out with NOTHING coming back — no returned follows and no
  // followers at all — reads high. Plenty of real people follow a few
  // accounts that don't follow back; they still have someone following them.
  const level = back === 0 && !followerIds.length ? "high" : back === 0 || ratio < 0.5 ? "medium" : "low";
  return { key: "reciprocity", label: "Follow reciprocity", value: `${back} of ${following.length} follows returned; followed by ${followerIds.length}`, level };
}

// `followerIds`: ids of the accounts (in the same world) that follow this
// one — passed in rather than looked up, so this file stays free of any
// world/roster state.
function computeDeepSignals(account, followerIds) {
  const deep = account.deep || {};
  return [
    timezoneSignal(deep, account),
    photoSignal(deep),
    recordSignal(deep, account),
    engagementSignal(deep),
    reciprocitySignal(account, followerIds || []),
  ].filter(Boolean);
}

const api = { computeSignals, computeDeepSignals, summarizeEngagement, formatUtcOffset, ALGO_LAUNCH };

if (typeof module !== "undefined" && module.exports) {
  module.exports = api;
} else {
  window.SKRAPERS_INVESTIGATE = api;
}

})();
